### ISSUE TITLE
User Permissions: Restricting the view of certain data

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-redash#10]
Originally mentioned in #3. 

As a client
I want to be able to view and query only part of my project's data
So that I do not breach the privacy terms of the application

We have a client who wants to be able to view and query all of their data apart from a couple of fields which should be kept confidential. Rather than restricting the client so that they can only view existing queries we want to be able to either block out or encrypt the field which is sensitive.

I came across this on the Redash FAQs:

From [Redash](http://help.redash.io/article/73-permissions-groups):

> **What if I want to limit the user to only some tables?**

> The idea is to leverage your database’s security model and hence create a user with access to the tables/columns you want to give access to. Create a data source that's using this user and then associate it with a group of users who need this level of access.
  
However I don't understand how to achieve this as my understanding is that the only available permission options are: 

<img src="https://user-images.githubusercontent.com/16775804/34616823-42f115cc-f231-11e7-9214-f20fd5f5e354.png" width=180px />

@arikfr - are you able to assist? 

Opened up a topic for discussion here: https://discuss.redash.io/t/user-permissions-obscuring-data-values-but-enabling-queries-creation/1370

**Comment by arikfr** [comment]
Thank you for moving the discussion to our forum -> I followed up there.

**Comment by iteles** [comment]
<img width="769" alt="screen shot 2018-01-09 at 13 32 27" src="https://user-images.githubusercontent.com/4185328/34723205-949c01a8-f541-11e7-90d4-74357a53f526.png">
