### ISSUE TITLE
How to write SQL queries

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-redash#5]
Find a good and simple tutorial for people wanting to learn basic SQL to use Redash.

To investigate:
https://community.modeanalytics.com/sql/tutorial/introduction-to-sql/
https://www.w3schools.com/sql/
https://www.codecademy.com/learn/learn-sql

**List of SQL commands:**
https://www.codecademy.com/articles/sql-commands?r=master

**Questions to ask:**
- do we only want to teach select/join statements?
- how much time do we think people have to invest in learning this?

**Comment by iteles** [comment]
A couple of simple examples in our readme and then directing people to a couple of good tutorials would work well. If we order the tutorials in the order of simplest to a little more complex then people have some flexibility around the time they invest.

If we can find a comparable MDN resource to replace w3schools, I would add that in, I still have hangups on w3schools from the old days :wink: https://github.com/OxfordAbstracts/application/issues/4893

**Comment by Cleop** [comment]
## Simple examples to include:

:bangbang: **NOTE: Any commands that use the words UPDATE, DROP, ALTER, CREATE, INSERT or DELETE will make permanent changes to your data, do not use them unless you have checked with your team that you are not using your site's live data.** :bangbang:

### Select data from one table

A query is a request you make to your database for some information. The most simple query you can run is one which displays data for you. So if your database had a table called 'People' that looked like this:

**People**

| User ID | Name     | Age | Occupation      |
|---------|----------|-----|-----------------|
| 1       | Amy      | 29  | Violinist       |
| 2       | Bob      | 55  | Tree Surgeon    |
| 3       | Clarissa | 42  | Physiotherapist |

and you wanted to write a query that would display all of this data to you you would write:

```SELECT * FROM people;```

In this command you are selecting all of the data (the asterisk represents all values) from your table called 'People'. All SQL commands must end with a semi-colon to indicate that this is the end of your query. 
  
### Select data from two tables

In order to display data from two tables together you can do an inner join. So if I wanted to combine the values from the people table above with the pets table:

| pet_id | pet_name | animal | owner_id |
|--------|----------|--------|----------|
| 9      | Fido     | Dog    | 1        |
| 10     | Tiddles  | Cat    | 1        |
| 11     | Spot     | Dog    | 2        |

You would write:

```
SELECT * FROM people
JOIN pets
ON people.user_id = pets.owner_id; 
```

An inner join will combine rows from different tables if the join condition is true. So joining the people and pets tables we would get a result like this:

| user_id | name | age | occupation   | pet_id | pet_name | animal | owner_id |
|---------|------|-----|--------------|--------|----------|--------|----------|
| 1       | Amy  | 29  | Violinist    | 9      | Fido     | Dog    | 1        |
| 1       | Amy  | 29  | Violinist    | 10     | Tiddles  | Cat    | 1        |
| 2       | Bob  | 55  | Tree Surgeon | 11     | Spot     | Dog    | 2        |

Notice how Amy appears twice because she has 2 pets whereas Clarissa no longer appears as she has no pets.

### Select one column of data

If you just want to see one column of data run the following command:

```
SELECT people.name
FROM people;
```

Which will give you:

| Name |
|------|
| Amy  |
| Amy  |
| Bob  |

## Further Learning
If you've got time to learn a bit more about SQL why not try the free codeacademy tutorial: 
https://www.codecademy.com/learn/learn-sql or this one from Mode: https://community.modeanalytics.com/sql/tutorial/introduction-to-sql/

If you are a bit more familiar with SQL check out this glossary of terms to remind you of some of the key phrases: https://www.codecademy.com/articles/sql-commands?r=master
