### ISSUE TITLE
Add examples use cases from projects to the readme

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-redash#7]
As someone learning Redash
I would like to know of some real world examples of how Redash is being used
So that I can have a better idea of how it might be useful for me

<hr/>

This might work well at the end for the `What` section.

**Comment by Cleop** [comment]
Some real world examples where Redash has proven helpful:

- A client creating a new application and looking to gain a better understanding of user's behaviours. Redash proved a helpful and more detailed layer to complement Google Analytics and Tag Manager.
 - A client with different user types on their platform looking to give their admins the ability to query and search their data to help the project management and give admins a better understanding of how the app is being used.
  
@iteles - I believe you have another example in mind to do with a client using Redash to assist with external report writing? Feel free to shorten or amend what I've written to blend the examples together or make them more succinct.

**Comment by iteles** [comment]
Indeed, one of our clients uses it as a reporting tool.

In essence, rather than having to build a bevy of reports (ranging from simple to complex) into the core of their application, many of which would be used only by one client or as a one-off, they have chosen to create these in Redash.
They'll create dashboards for their clients and this also reduces the client team's dependence on developers.
